import 'package:flutter/material.dart';
import '../models/course_model.dart';
import '../models/document_model.dart';
import '../models/document_type.dart';

/// Dữ liệu mẫu khởi tạo ban đầu cho ứng dụng
class MockInitialData {
  static List<CourseModel> getInitialCourses() {
    final now = DateTime.now();
    return [
      CourseModel(
        courseId: 'course_cse441',
        name: 'Lập trình Di động',
        code: 'CSE441',
        description: 'Phát triển ứng dụng di động đa nền tảng với Flutter & Dart',
        color: const Color(0xFF0288D1),
        icon: Icons.phone_android_rounded,
        order: 1,
        dateCreated: now.subtract(const Duration(days: 30)),
      ),
      CourseModel(
        courseId: 'course_cse381',
        name: 'Cấu trúc Dữ liệu & Giải thuật',
        code: 'CSE381',
        description: 'Giải thuật tìm kiếm, sắp xếp, đồ thị và cây nhị phân',
        color: const Color(0xFF7B1FA2),
        icon: Icons.account_tree_rounded,
        order: 2,
        dateCreated: now.subtract(const Duration(days: 30)),
      ),
      CourseModel(
        courseId: 'course_cse484',
        name: 'Cơ sở Dữ liệu Phân tán',
        code: 'CSE484',
        description: 'Kiến trúc CSDL phân tán, NoSQL, sao lưu và đồng bộ',
        color: const Color(0xFF00897B),
        icon: Icons.storage_rounded,
        order: 3,
        dateCreated: now.subtract(const Duration(days: 30)),
      ),
      CourseModel(
        courseId: 'course_cse405',
        name: 'Mạng Máy tính Nâng cao',
        code: 'CSE405',
        description: 'Giao thức mạng TCP/IP, định tuyến và an ninh mạng',
        color: const Color(0xFFE65100),
        icon: Icons.hub_rounded,
        order: 4,
        dateCreated: now.subtract(const Duration(days: 30)),
      ),
    ];
  }

  static List<DocumentModel> getInitialDocuments() {
    final now = DateTime.now();
    return [
      DocumentModel(
        id: 'doc_1',
        title: 'Chương 1: Kiến trúc Flutter & Reactive State Management',
        description: 'Bài giảng chi tiết về Widget tree, Element tree, RenderObject và Provider pattern.',
        courseId: 'course_cse441',
        type: DocumentType.lecture,
        status: StudyStatus.completed,
        priority: PriorityLevel.high,
        fileUrl: 'https://flutter.dev/docs/resources/architectural-overview',
        pageCount: 42,
        estimatedMinutes: 60,
        isPinned: true,
        dateCreated: now.subtract(const Duration(days: 10)),
        completedDate: now.subtract(const Duration(days: 2)),
        tags: ['Flutter', 'StateManagement', 'Provider'],
      ),
      DocumentModel(
        id: 'doc_2',
        title: 'Bài tập Thực hành 1: Xây dựng App theo Kiến trúc Cashew',
        description: 'Áp dụng nguyên lý Local-first, Reactive Streams và phân lớp kiến trúc hệ thống.',
        courseId: 'course_cse441',
        type: DocumentType.exercise,
        status: StudyStatus.inProgress,
        priority: PriorityLevel.high,
        fileUrl: 'https://github.com/iam-mia/cse441-team13',
        pageCount: 15,
        estimatedMinutes: 180,
        isPinned: true,
        dateCreated: now.subtract(const Duration(days: 5)),
        dueDate: now.add(const Duration(days: 3)),
        tags: ['Cashew', 'Architecture', 'TH1'],
      ),
      DocumentModel(
        id: 'doc_3',
        title: 'Tài liệu Tham khảo: Effective Dart & Clean Code',
        description: 'Quy chuẩn đặt tên, phong cách code chuẩn Google và best practices trong lập trình Dart.',
        courseId: 'course_cse441',
        type: DocumentType.reference,
        status: StudyStatus.pending,
        priority: PriorityLevel.medium,
        fileUrl: 'https://dart.dev/guides/language/effective-dart',
        pageCount: 30,
        estimatedMinutes: 45,
        isPinned: false,
        dateCreated: now.subtract(const Duration(days: 4)),
        tags: ['Dart', 'CleanCode', 'Reference'],
      ),
      DocumentModel(
        id: 'doc_4',
        title: 'Bài giảng Cây đỏ đen (Red-Black Trees) và Ứng dụng',
        description: 'Nguyên lý cân bằng cây nhị phân tìm kiếm, phép xoay cây và độ phức tạp tính toán.',
        courseId: 'course_cse381',
        type: DocumentType.lecture,
        status: StudyStatus.inProgress,
        priority: PriorityLevel.medium,
        fileUrl: 'https://mit.edu/algorithms/red-black-trees.pdf',
        pageCount: 28,
        estimatedMinutes: 50,
        isPinned: false,
        dateCreated: now.subtract(const Duration(days: 12)),
        tags: ['DataStructures', 'Tree', 'Algorithm'],
      ),
      DocumentModel(
        id: 'doc_5',
        title: 'Đề thi Giữa kỳ Môn Cấu trúc Dữ liệu năm 2025 kèm Lời giải',
        description: 'Tổng hợp 15 bài toán quy hoạch động, cây đồ thị và phân tích Big-O.',
        courseId: 'course_cse381',
        type: DocumentType.exam,
        status: StudyStatus.pending,
        priority: PriorityLevel.high,
        fileUrl: 'https://storage.example.com/exam_cse381_midterm.pdf',
        pageCount: 12,
        estimatedMinutes: 90,
        isPinned: true,
        dateCreated: now.subtract(const Duration(days: 8)),
        dueDate: now.add(const Duration(days: 7)),
        tags: ['Exam', 'Midterm', 'DSA'],
      ),
      DocumentModel(
        id: 'doc_6',
        title: 'Bài giảng Định lý CAP và Tính nhất quán Dữ liệu (Consistency)',
        description: 'So sánh ACID và BASE, phân tích định lý Brewer trong hệ phân tán hiện đại.',
        courseId: 'course_cse484',
        type: DocumentType.lecture,
        status: StudyStatus.completed,
        priority: PriorityLevel.low,
        fileUrl: 'https://storage.example.com/cap_theorem_slides.pdf',
        pageCount: 35,
        estimatedMinutes: 40,
        isPinned: false,
        dateCreated: now.subtract(const Duration(days: 15)),
        completedDate: now.subtract(const Duration(days: 5)),
        tags: ['Distributed', 'CAP', 'Database'],
      ),
      DocumentModel(
        id: 'doc_7',
        title: 'Bài tập Lớn: Thiết kế Cụm CSDL Phân tán NoSQL Sharding',
        description: 'Triển khai mô hình phân mảnh dữ liệu (Sharding) và bản sao lưu (Replication).',
        courseId: 'course_cse484',
        type: DocumentType.exercise,
        status: StudyStatus.pending,
        priority: PriorityLevel.high,
        fileUrl: 'https://storage.example.com/assignment_sharding.pdf',
        pageCount: 8,
        estimatedMinutes: 240,
        isPinned: false,
        dateCreated: now.subtract(const Duration(days: 3)),
        dueDate: now.add(const Duration(days: 14)),
        tags: ['NoSQL', 'Sharding', 'Project'],
      ),
      DocumentModel(
        id: 'doc_8',
        title: 'Bộ Đề thi Cuối kỳ Mạng Máy tính & Mô phỏng Wireshark',
        description: 'Phân tích gói tin TCP 3-way handshake và kiểm tra bảo mật TLS/SSL.',
        courseId: 'course_cse405',
        type: DocumentType.exam,
        status: StudyStatus.pending,
        priority: PriorityLevel.medium,
        fileUrl: 'https://storage.example.com/wireshark_labs.pdf',
        pageCount: 20,
        estimatedMinutes: 120,
        isPinned: false,
        dateCreated: now.subtract(const Duration(days: 6)),
        tags: ['Network', 'Wireshark', 'Exam'],
      ),
    ];
  }
}
